<?php
require 'auth.php'; require_login(); require 'db.php'; require 'layout.php';
if($_SERVER['REQUEST_METHOD']==='POST'){
    require_volunteer(); verify_csrf();
    if(isset($_POST['add_vet'])){
        $name=trim($_POST['vet_name']??'');$avail=trim($_POST['availability_status']??'Available');$spec=trim($_POST['specialization']??'');$qual=trim($_POST['qualification']??'');$yrs=max(0,(int)($_POST['experienced_years']??0));$email=trim($_POST['email']??'');$lic=trim($_POST['license_no']??'');$phone=trim($_POST['phone_number']??'');
        if($name===''||$spec===''||$qual===''||!filter_var($email,FILTER_VALIDATE_EMAIL)||$lic==='') redirect_with_message('treatments.php','Enter valid veterinarian information.');
        try{$s=$conn->prepare('INSERT INTO vets(vet_name,availability_status,specialization,qualification,experienced_years,email,license_no,phone_number) VALUES(?,?,?,?,?,?,?,?)');$s->bind_param('ssssisss',$name,$avail,$spec,$qual,$yrs,$email,$lic,$phone);$s->execute();redirect_with_message('treatments.php','Veterinarian added.');}catch(mysqli_sql_exception $e){redirect_with_message('treatments.php','That veterinarian license number already exists.');}
    }
    $vet=(int)($_POST['vet_id']??0);$animal=(int)($_POST['animal_id']??0);$time=str_replace('T',' ',trim($_POST['treatment_time']??''));$type=$_POST['treatment_type']??'';$status=$_POST['status']??'';$med=trim($_POST['medication']??'');$other=trim($_POST['others']??'');$desc=trim($_POST['description']??'');
    if($vet<=0||$animal<=0||$time===''||!in_array($type,['vaccination','surgery','medication','other'],true)||!in_array($status,['ongoing','completed','cancelled'],true)||$desc==='') redirect_with_message('treatments.php','Complete the required treatment information.');
    $uid=(int)$_SESSION['user_id'];
    $conn->begin_transaction();
    try{$s=$conn->prepare('INSERT INTO treatment(vet_id,animal_id,treatment_time,treatment_type,status,medication,others) VALUES(?,?,?,?,?,?,?)');$s->bind_param('iisssss',$vet,$animal,$time,$type,$status,$med,$other);$s->execute();$tid=$conn->insert_id;$d=$conn->prepare('INSERT INTO treatment_description(treatment_id,description) VALUES(?,?)');$d->bind_param('is',$tid,$desc);$d->execute();
        if($status!=='cancelled'){$a=$conn->prepare("UPDATE animal SET status='under_treatment' WHERE animal_id=? AND status<>'adopted'");$a->bind_param('i',$animal);$a->execute();if($a->affected_rows){$h=$conn->prepare("INSERT INTO animal_status_history(animal_id,status,changed_by) VALUES(?,'under_treatment',?)");$h->bind_param('ii',$animal,$uid);$h->execute();}}
        $conn->commit();redirect_with_message('treatments.php','Treatment recorded.');
    }catch(Throwable $e){$conn->rollback();throw $e;}
}
$animals=$conn->query("SELECT animal_id,name FROM animal WHERE status<>'adopted' ORDER BY name");$vets=$conn->query('SELECT * FROM vets ORDER BY vet_name');$vets2=$conn->query('SELECT * FROM vets ORDER BY vet_name');$rows=$conn->query('SELECT t.*,a.name animal_name,v.vet_name,d.description FROM treatment t JOIN animal a ON t.animal_id=a.animal_id JOIN vets v ON t.vet_id=v.vet_id LEFT JOIN treatment_description d ON t.treatment_id=d.treatment_id ORDER BY t.treatment_time DESC,t.treatment_id DESC');page_top('Treatments');
?>
<div class="section-head"><h1 class="page-title">Veterinary & Treatment</h1></div>
<?php if(is_volunteer()):?><div class="grid">
<form class="form-card form-grid" method="post"><?=csrf_field()?><h2 class="full">Record treatment</h2><select name="animal_id" required><option value="">Animal</option><?php while($a=$animals->fetch_assoc()):?><option value="<?=$a['animal_id']?>"><?=h($a['name'])?></option><?php endwhile;?></select><select name="vet_id" required><option value="">Vet</option><?php while($v=$vets->fetch_assoc()):?><option value="<?=$v['vet_id']?>"><?=h($v['vet_name'])?></option><?php endwhile;?></select><input type="datetime-local" name="treatment_time" value="<?=date('Y-m-d\TH:i')?>" required><select name="treatment_type"><option value="vaccination">Vaccination</option><option value="surgery">Surgery</option><option value="medication">Medication</option><option value="other">Other</option></select><select name="status"><option value="ongoing">Ongoing</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><input name="medication" placeholder="Medication"><textarea class="full" name="description" placeholder="Treatment description" required></textarea><textarea class="full" name="others" placeholder="Other notes"></textarea><button class="btn full">Save Treatment</button></form>
<form class="form-card form-grid" method="post"><?=csrf_field()?><h2 class="full">Add veterinarian</h2><input type="hidden" name="add_vet" value="1"><input name="vet_name" placeholder="Vet name" required><input name="specialization" placeholder="Specialization" required><input name="qualification" placeholder="Qualification" required><input type="number" name="experienced_years" min="0" placeholder="Years experience"><input type="email" name="email" placeholder="Email" required><input name="phone_number" placeholder="Phone"><input name="license_no" placeholder="License number" required><select name="availability_status"><option>Available</option><option>Busy</option><option>Unavailable</option></select><button class="btn full">Add Vet</button></form>
</div><?php endif;?>
<div class="section-head"><h2>Veterinarians</h2></div><div class="grid"><?php if($vets2->num_rows===0):?><div class="empty card">No veterinarians added yet.</div><?php endif;?><?php while($v=$vets2->fetch_assoc()):?><div class="card"><h3>Dr. <?=h($v['vet_name'])?></h3><p><?=h($v['specialization'])?><br><?=h($v['qualification'])?><br><?=h($v['experienced_years'])?> years experience</p><span class="tag"><?=h($v['availability_status'])?></span><p class="muted"><?=h($v['email'])?> · <?=h($v['phone_number']?:'No phone')?></p></div><?php endwhile;?></div>
<div class="section-head"><h2>Treatment history</h2></div><div class="table-wrap"><table><tr><th>Animal</th><th>Vet</th><th>Date</th><th>Type</th><th>Status</th><th>Description</th></tr><?php while($r=$rows->fetch_assoc()):?><tr><td><?=h($r['animal_name'])?></td><td><?=h($r['vet_name'])?></td><td><?=h($r['treatment_time'])?></td><td><?=h(ucfirst($r['treatment_type']))?></td><td><span class="tag"><?=h($r['status'])?></span></td><td><?=h($r['description']??'')?></td></tr><?php endwhile;?></table></div>
<?php page_bottom(); ?>
